from app import db

class TeamPit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    team_number = db.Column(db.Integer)
    drivetrain = db.Column(db.String)
    wheels_number = db.Column(db.Integer)
    wheels_type = db.Column(db.String)
    motors_number = db.Column(db.Integer)
    motors_type = db.Column(db.String)
    speed = db.Column(db.Float)
    weight = db.Column(db.Float)
    height = db.Column(db.Float)
    fit_under_trench = db.Column(db.Boolean)
    rendezvous_cycles = db.Column(db.Integer)
    auto_move = db.Column(db.Boolean)
    auto_score_lower = db.Column(db.Boolean)
    auto_score_outer = db.Column(db.Boolean)
    auto_score_inner = db.Column(db.Boolean)
    auto_ball_number = db.Column(db.Integer)
    auto_collect_balls = db.Column(db.Boolean)
    auto_consistency = db.Column(db.Integer)
    teleop_score_lower = db.Column(db.Boolean)
    teleop_score_outer = db.Column(db.Boolean)
    teleop_score_inner = db.Column(db.Boolean)
    teleop_consistency = db.Column(db.Integer)
    control_panel_rotation = db.Column(db.Boolean)
    control_panel_position = db.Column(db.Boolean)
    hang = db.Column(db.Boolean)
    hang_level = db.Column(db.Boolean)
    hang_active = db.Column(db.Boolean)
    hang_position = db.Column(db.String)
    hang_consistency = db.Column(db.Integer)
    honest = db.Column(db.String)
    answer = db.Column(db.String)
    notes = db.Column(db.String)

    def __repr__(self):
        return(self.id)

class TeamMatch(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    team_number = db.Column(db.Integer)
    match_number = db.Column(db.Integer)
    alliance = db.Column(db.String)
    station_number = db.Column(db.Integer)
    auto_move = db.Column(db.Boolean)
    auto_score_lower = db.Column(db.Boolean)
    auto_score_outer = db.Column(db.Boolean)
    auto_score_inner = db.Column(db.Boolean)
    auto_ball_number = db.Column(db.Integer)
    auto_collect_balls = db.Column(db.Boolean)
    teleop_score_lower = db.Column(db.Boolean)
    teleop_score_outer = db.Column(db.Boolean)
    teleop_score_inner = db.Column(db.Boolean)
    teleop_ball_number = db.Column(db.Integer)
    teleop_consistency = db.Column(db.Integer)
    control_panel_rotation = db.Column(db.Boolean)
    control_panel_position = db.Column(db.Boolean)
    hang = db.Column(db.Boolean)
    hang_level = db.Column(db.Boolean)
    hang_active = db.Column(db.Boolean)
    hang_position = db.Column(db.String)
    defense = db.Column(db.Integer)
    penalties = db.Column(db.Integer)
    connection_issue = db.Column(db.Boolean)
    brownout = db.Column(db.Boolean)
    turn_off = db.Column(db.Boolean)
    notes = db.Column(db.String)

        def __repr__(self):
        return(self.id)

class Drivetrain(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

class Wheel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

class Motor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)