"""empty message

Revision ID: 19dd3c1bed2d
Revises: 
Create Date: 2020-02-23 23:58:17.498265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd3c1bed2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_pit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('drivetrain_type', sa.String(), nullable=True),
    sa.Column('wheel_type', sa.String(), nullable=True),
    sa.Column('wheel_number', sa.Integer(), nullable=True),
    sa.Column('motor_type', sa.String(), nullable=True),
    sa.Column('motor_number', sa.String(), nullable=True),
    sa.Column('drivetrain_notes', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('auto_move', sa.Boolean(), nullable=True),
    sa.Column('auto_score_lower', sa.Boolean(), nullable=True),
    sa.Column('auto_score_outer', sa.Boolean(), nullable=True),
    sa.Column('auto_score_inner', sa.Boolean(), nullable=True),
    sa.Column('auto_collect_balls', sa.Boolean(), nullable=True),
    sa.Column('auto_consistency', sa.Integer(), nullable=True),
    sa.Column('auto_prefered_position', sa.String(), nullable=True),
    sa.Column('teleop_score_lower', sa.Boolean(), nullable=True),
    sa.Column('teleop_score_outer', sa.Boolean(), nullable=True),
    sa.Column('teleop_score_inner', sa.Boolean(), nullable=True),
    sa.Column('teleop_consistency', sa.Integer(), nullable=True),
    sa.Column('teleop_prefered_position', sa.String(), nullable=True),
    sa.Column('control_panel_rotation', sa.Boolean(), nullable=True),
    sa.Column('control_panel_postition', sa.Boolean(), nullable=True),
    sa.Column('hang_able', sa.Boolean(), nullable=True),
    sa.Column('hang_level', sa.Boolean(), nullable=True),
    sa.Column('hang_prefered_position', sa.String(), nullable=True),
    sa.Column('hang_consistency', sa.Integer(), nullable=True),
    sa.Column('hang_time', sa.Float(), nullable=True),
    sa.Column('hang_active', sa.Boolean(), nullable=True),
    sa.Column('personnel_honest', sa.Integer(), nullable=True),
    sa.Column('personnel_answer', sa.Integer(), nullable=True),
    sa.Column('personnel_notes', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=True),
    sa.Column('alliance', sa.String(), nullable=True),
    sa.Column('station', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('auto_move', sa.Boolean(), nullable=True),
    sa.Column('auto_score_lower', sa.Integer(), nullable=True),
    sa.Column('auto_score_upper', sa.Integer(), nullable=True),
    sa.Column('auto_collect_balls', sa.Boolean(), nullable=True),
    sa.Column('auto_points', sa.Integer(), nullable=True),
    sa.Column('teleop_score_lower', sa.Integer(), nullable=True),
    sa.Column('teleop_score_upper', sa.Integer(), nullable=True),
    sa.Column('teleop_points', sa.Integer(), nullable=True),
    sa.Column('teleop_attempts', sa.Integer(), nullable=True),
    sa.Column('teleop_success_rate', sa.Float(), nullable=True),
    sa.Column('control_panel_rotation', sa.Boolean(), nullable=True),
    sa.Column('control_panel_position', sa.Boolean(), nullable=True),
    sa.Column('control_panel_points', sa.Integer(), nullable=True),
    sa.Column('hang_able', sa.Boolean(), nullable=True),
    sa.Column('hang_level', sa.Boolean(), nullable=True),
    sa.Column('hang_position', sa.String(), nullable=True),
    sa.Column('hang_active', sa.Boolean(), nullable=True),
    sa.Column('hang_points', sa.Integer(), nullable=True),
    sa.Column('defense_performance', sa.Integer(), nullable=True),
    sa.Column('defense_penalties', sa.Integer(), nullable=True),
    sa.Column('connection_issues', sa.Integer(), nullable=True),
    sa.Column('brownouts', sa.Integer(), nullable=True),
    sa.Column('emergency_stop', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_report')
    op.drop_table('team_pit')
    op.drop_table('match')
    # ### end Alembic commands ###
