"""empty message

Revision ID: 1ac966d9c3c6
Revises: 
Create Date: 2020-02-20 22:27:15.828183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac966d9c3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=True),
    sa.Column('hang', sa.Boolean(), nullable=True),
    sa.Column('balanced', sa.Boolean(), nullable=True),
    sa.Column('score_lower', sa.Boolean(), nullable=True),
    sa.Column('score_outer', sa.Boolean(), nullable=True),
    sa.Column('score_inner', sa.Boolean(), nullable=True),
    sa.Column('control_panel', sa.Boolean(), nullable=True),
    sa.Column('auto_move', sa.Boolean(), nullable=True),
    sa.Column('auto_score_lower', sa.Boolean(), nullable=True),
    sa.Column('auto_score_outer', sa.Boolean(), nullable=True),
    sa.Column('auto_score_inner', sa.Boolean(), nullable=True),
    sa.Column('drivetrain', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
